projekt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'projekt.views.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
    {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    url(r'^wyslij/', 'projekt.views.wyslij'),
    url(r'^odbierz/', 'projekt.views.odbierz'),
    url(r'^logowanie/', 'projekt.views.logowanie'),
    url(r'^rejestracja/', 'projekt.views.rejestracja'),
    url(r'^auth/', 'projekt.views.l_auth'),
    url(r'^wyloguj/', 'projekt.views.wyloguj'),

    # url(r'^projekt/', include('projekt.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

projekt/models.py
from django.db import models

class Wiad(models.Model):
    message=models.TextField()
    user=models.CharField(max_length=35)
    timestamp=models.DateTimeField()

    def __unicode__(self):
        return self.tytul

projekt/forms.py
from django.forms import ModelForm
from django import forms
from models import Wiad

class Formularz(forms.ModelForm):
     class Meta:
         model = Wiad
         widgets = {
            'message': forms.TextInput,
         }
         fields = ['message']

projekt/views.py
from models import Wiad
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.context_processors import  csrf
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
import datetime
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from forms import Formularz
from django.contrib.auth.models import User
import requests
import json
import tasks
import simplejson as sjson

def home(request):
    tasks.rejestracja.delay()
    form=Formularz()

    return render_to_response("index.html",
    {'wpisy' : Wiad.objects.all().order_by("-id"),"form":form},
    context_instance=RequestContext(request),)

def wyslij(request):
    if request.method == 'POST': # If the form has been submitted...
        wiad=Wiad()
        if request.user.is_authenticated():
            form = Formularz(request.POST) # A form bound to the POST data
            if form.is_valid(): # All validation rules pass
                message=form.cleaned_data["message"]
                user=request.user.username
                timestamp=datetime.datetime.now()

                tasks.wyslij.delay(user,message,timestamp)

                wiad.message=message
                wiad.user=user+"@local"
                wiad.timestamp=timestamp
                wiad.save()

    return HttpResponseRedirect(reverse('projekt.views.home'))

def odbierz(request):
    if request.method == 'POST': # If the form has been submitted...
        wiad=Wiad()
        data = sjson.loads(request.body)
        message=data["message"]
        user=data["user"]
        timestamp=data["timestamp"]

        wiad.message=str(message)
        wiad.user=str(user+"@"+get_client_ip(request))
        wiad.timestamp=datetime.datetime(timestamp)
        wiad.save()

        return HttpResponse(" ")


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def logowanie(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('logowanie.html', c,
                                context_instance=RequestContext(request),)

def l_auth(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username = username, password=password)

    if user is not None:
        if user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('projekt.views.home'))
    else:
        return HttpResponseRedirect(reverse('projekt.views.logowanie'))



def wyloguj(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('projekt.views.home'))


def rejestracja(request):
    form = UserCreationForm(request.POST)
    args= {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('projekt.views.logowanie'))
        else:
            args['wiad'] = "Wypelnij poprawnie wszystkie pola lub takie konto juz istnieje"
    print args
    return render_to_response('rejestracja.html', args,
                            context_instance=RequestContext(request),)

projekt/templates/base.html
<html>

<head>
<style>

body{
text-align:center;
font-family:Tahoma,sans-serif;
}

.form{
    marign-top:10px;
    padding-bottom: 10px;
    padding-top: 10px;
    background-color: lightgrey;
}

.calosc{
    width:800px;
    text-align: left;
    margin-left:auto;
    margin-right:auto;
}

.naglowek{
    font-size:27px;
    padding-bottom: 5px;
    text-align: center;
    width:100%;
}

.wpis{
    vertical-align: top;
}

.nick{
    display: inline-block;
    margin-left:50px;
    font-style:italic;
    vertical-align: middle;
}

.tresc{
    margin-top: 5px;
    display:inline-block;
}

a:visited{
    text-decoration: none;
    color:black;
}

a{
    text-decoration: none;
    color:black;
}

.podpis
{
    margin-top: 10px;
    font-style:italic;
}

    .logowanie{
        position: absolute;
        right:10px;
        top:10px;
        text-align:right;
    }

#id_message{
width:670px;
}

.wpisy{
    border-width: 3px;
    border-color:black;
    border-style:solid;
}

</style>

</head>

<body>
<center>
<div class="calosc">
<div class="naglowek">
    <a href="{% url 'projekt.views.home' %}">Django chat</a href>
</div>

{% block content %}

{% endblock %}
</div>
</center>
</body>

</html>

projekt/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="logowanie">
{% if user.is_authenticated %}
Hej, {{ user.username }}!<br>
<a href="{% url 'projekt.views.wyloguj' %}">Wyloguj</a>
{% else %}
<a href="{% url 'projekt.views.logowanie' %}">Zaloguj</a>
{% endif %}
</div>

    {% if user.is_authenticated %}
<form class="form" action="{% url 'projekt.views.wyslij'%}" method="post">{% csrf_token %}
{{ form }}
<input type="submit" value="Wyślij" />
</form>
{% endif %}
<div class="wpisy">
{% for wpis in wpisy %}

<div class="wpis">

<div class="nick">
<b>{{ wpis.user }}</b>&nbsp;({{ wpis.timestamp|date:"d M, H:i"}}):
</div>&nbsp;

<div class="tresc">
{{ wpis.message }}
</div>

</a>
</div>

{% endfor %}
</div>

{% endblock %}

projekt/templates/logowanie.html
{% extends "base.html" %}

{% block content %}

<div class="logowanie">
<a href="{% url 'projekt.views.rejestracja' %}">Rejestracja</a>
</div>

    {%  if form.errors %}
        <p class="error">Przykro mi, podales zle haslo lub login </p>
    {% endif %}
    <div class="tytul">Logowanie</div>
    <form style="margin-top: 10px;" action="{%  url 'projekt.views.l_auth' %}" method="post">{% csrf_token %}
        <label for="username">Login: </label>
        <input type="text" name="username" value="" id="username">
        <label for="password">Haslo: </label>
        <input type="password" name="password" value="" id="password">

        <input type="submit" value="Zaloguj" />

    </form>

{% endblock %}

projekt/templates/rejestracja.html
{%  extends "base.html" %}

{% block content %}

<div class="tytul">Rejestracja</div>
    {%  if wiad %}
        <p style="color:#ff3f3e" >{{ wiad }} </p>
    {% endif %}
    <form action="{% url 'projekt.views.rejestracja' %}" method="post">{% csrf_token %}
        <table>
    {{ form.as_table }}
        </table>
    <input type="submit" value="Zarejestruj" />
    </form>

{% endblock %}